# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy to Heroku
        uses: gonuit/heroku-docker-deploy@v1.2.0
        with:

          # Below you must provide variables for your Heroku app.
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com

          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dokerfile name. Optional, by default will be set to "Dockerfile".
          dockerfile_name: Dockerfile

          # Additional options of docker build command. (Optional)
          # docker_options: "--no-cache"

          # Dokerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./

